# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arbitrary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='arbitrary.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61rbitrary.proto\x1a\nbase.proto\"3\n\x18SecurityArbitraryRequest\x12\x17\n\x0fnum_simulations\x18\x01 \x01(\r\"3\n\x18\x43urrencyArbitraryRequest\x12\x17\n\x0fnum_simulations\x18\x01 \x01(\r2\xa7\x01\n\x13\x41rbitrarySimulation\x12G\n\x17StreamSecurityArbitrary\x12\x19.SecurityArbitraryRequest\x1a\r.SecurityBase\"\x00\x30\x01\x12G\n\x17StreamCurrencyArbitrary\x12\x19.CurrencyArbitraryRequest\x1a\r.CurrencyBase\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[base__pb2.DESCRIPTOR,])




_SECURITYARBITRARYREQUEST = _descriptor.Descriptor(
  name='SecurityArbitraryRequest',
  full_name='SecurityArbitraryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_simulations', full_name='SecurityArbitraryRequest.num_simulations', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=82,
)


_CURRENCYARBITRARYREQUEST = _descriptor.Descriptor(
  name='CurrencyArbitraryRequest',
  full_name='CurrencyArbitraryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_simulations', full_name='CurrencyArbitraryRequest.num_simulations', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['SecurityArbitraryRequest'] = _SECURITYARBITRARYREQUEST
DESCRIPTOR.message_types_by_name['CurrencyArbitraryRequest'] = _CURRENCYARBITRARYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecurityArbitraryRequest = _reflection.GeneratedProtocolMessageType('SecurityArbitraryRequest', (_message.Message,), {
  'DESCRIPTOR' : _SECURITYARBITRARYREQUEST,
  '__module__' : 'arbitrary_pb2'
  # @@protoc_insertion_point(class_scope:SecurityArbitraryRequest)
  })
_sym_db.RegisterMessage(SecurityArbitraryRequest)

CurrencyArbitraryRequest = _reflection.GeneratedProtocolMessageType('CurrencyArbitraryRequest', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYARBITRARYREQUEST,
  '__module__' : 'arbitrary_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyArbitraryRequest)
  })
_sym_db.RegisterMessage(CurrencyArbitraryRequest)



_ARBITRARYSIMULATION = _descriptor.ServiceDescriptor(
  name='ArbitrarySimulation',
  full_name='ArbitrarySimulation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=138,
  serialized_end=305,
  methods=[
  _descriptor.MethodDescriptor(
    name='StreamSecurityArbitrary',
    full_name='ArbitrarySimulation.StreamSecurityArbitrary',
    index=0,
    containing_service=None,
    input_type=_SECURITYARBITRARYREQUEST,
    output_type=base__pb2._SECURITYBASE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamCurrencyArbitrary',
    full_name='ArbitrarySimulation.StreamCurrencyArbitrary',
    index=1,
    containing_service=None,
    input_type=_CURRENCYARBITRARYREQUEST,
    output_type=base__pb2._CURRENCYBASE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARBITRARYSIMULATION)

DESCRIPTOR.services_by_name['ArbitrarySimulation'] = _ARBITRARYSIMULATION

# @@protoc_insertion_point(module_scope)
