# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import arbitrary_pb2 as arbitrary__pb2
import base_pb2 as base__pb2


class ArbitrarySimulationStub(object):
    """Arbitrary service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSecurityArbitrary = channel.unary_stream(
                '/ArbitrarySimulation/StreamSecurityArbitrary',
                request_serializer=arbitrary__pb2.SecurityArbitraryRequest.SerializeToString,
                response_deserializer=base__pb2.SecurityBase.FromString,
                )
        self.StreamCurrencyArbitrary = channel.unary_stream(
                '/ArbitrarySimulation/StreamCurrencyArbitrary',
                request_serializer=arbitrary__pb2.CurrencyArbitraryRequest.SerializeToString,
                response_deserializer=base__pb2.CurrencyBase.FromString,
                )


class ArbitrarySimulationServicer(object):
    """Arbitrary service definition
    """

    def StreamSecurityArbitrary(self, request, context):
        """Creates random trade data to be sent back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCurrencyArbitrary(self, request, context):
        """Creates random trade data for currencies to be sent back to Orbit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArbitrarySimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSecurityArbitrary': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSecurityArbitrary,
                    request_deserializer=arbitrary__pb2.SecurityArbitraryRequest.FromString,
                    response_serializer=base__pb2.SecurityBase.SerializeToString,
            ),
            'StreamCurrencyArbitrary': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCurrencyArbitrary,
                    request_deserializer=arbitrary__pb2.CurrencyArbitraryRequest.FromString,
                    response_serializer=base__pb2.CurrencyBase.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArbitrarySimulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArbitrarySimulation(object):
    """Arbitrary service definition
    """

    @staticmethod
    def StreamSecurityArbitrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ArbitrarySimulation/StreamSecurityArbitrary',
            arbitrary__pb2.SecurityArbitraryRequest.SerializeToString,
            base__pb2.SecurityBase.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamCurrencyArbitrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ArbitrarySimulation/StreamCurrencyArbitrary',
            arbitrary__pb2.CurrencyArbitraryRequest.SerializeToString,
            base__pb2.CurrencyBase.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
