# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbase.proto\"2\n\x0cSecurityBase\x12\x13\n\x0bsecurity_id\x18\x01 \x01(\r\x12\r\n\x05price\x18\x02 \x01(\x01\":\n\x0c\x43urrencyBase\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x62\x61nk\x18\x02 \x01(\t\x12\x0e\n\x06quoted\x18\x03 \x01(\x01\x62\x06proto3'
)




_SECURITYBASE = _descriptor.Descriptor(
  name='SecurityBase',
  full_name='SecurityBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='security_id', full_name='SecurityBase.security_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='SecurityBase.price', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=64,
)


_CURRENCYBASE = _descriptor.Descriptor(
  name='CurrencyBase',
  full_name='CurrencyBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CurrencyBase.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bank', full_name='CurrencyBase.bank', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quoted', full_name='CurrencyBase.quoted', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['SecurityBase'] = _SECURITYBASE
DESCRIPTOR.message_types_by_name['CurrencyBase'] = _CURRENCYBASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecurityBase = _reflection.GeneratedProtocolMessageType('SecurityBase', (_message.Message,), {
  'DESCRIPTOR' : _SECURITYBASE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:SecurityBase)
  })
_sym_db.RegisterMessage(SecurityBase)

CurrencyBase = _reflection.GeneratedProtocolMessageType('CurrencyBase', (_message.Message,), {
  'DESCRIPTOR' : _CURRENCYBASE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyBase)
  })
_sym_db.RegisterMessage(CurrencyBase)


# @@protoc_insertion_point(module_scope)
