# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc



class OrbitAnalysisStub(object):
    """message CallStack {}

    This is for Orbit sending it's instrumentation stats back over for analysis
    rpc SendFinalStats (OrbitStats) returns ...
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """


class OrbitAnalysisServicer(object):
    """message CallStack {}

    This is for Orbit sending it's instrumentation stats back over for analysis
    rpc SendFinalStats (OrbitStats) returns ...
    """


def add_OrbitAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrbitAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrbitAnalysis(object):
    """message CallStack {}

    This is for Orbit sending it's instrumentation stats back over for analysis
    rpc SendFinalStats (OrbitStats) returns ...
    """
