# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade_simulation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade_simulation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16trade_simulation.proto\"]\n\tTradeData\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\x13\n\x0bsecurity_id\x18\x02 \x01(\r\x12\x0c\n\x04side\x18\x03 \x01(\r\x12\r\n\x05price\x18\x04 \x01(\x04\x12\x10\n\x08quantity\x18\x05 \x01(\r\"u\n\x15TradeArbitrageRequest\x12\x19\n\x05trade\x18\x01 \x01(\x0b\x32\n.TradeData\x12\x17\n\x0fnum_simulations\x18\x02 \x01(\r\x12\x15\n\rid_arbitrages\x18\x03 \x03(\r\x12\x11\n\tnum_dummy\x18\x04 \x01(\r\"c\n\x15TradeArbitraryRequest\x12\x19\n\x05trade\x18\x01 \x01(\x0b\x32\n.TradeData\x12\x17\n\x0fnum_simulations\x18\x02 \x01(\r\x12\x16\n\x0enum_securities\x18\x03 \x01(\r\"-\n\x16HistoricalTradeRequest\x12\x13\n\x0bsecurity_id\x18\x01 \x01(\r\"K\n\x17HistoricalTradeResponse\x12\x15\n\rhistory_found\x18\x01 \x01(\x08\x12\x19\n\x05trade\x18\x02 \x03(\x0b\x32\n.TradeData2\xe4\x01\n\x0fTradeSimulation\x12?\n\x15\x43reateArbitrageStream\x12\x16.TradeArbitrageRequest\x1a\n.TradeData\"\x00\x30\x01\x12?\n\x15\x43reateArbitraryStream\x12\x16.TradeArbitraryRequest\x1a\n.TradeData\"\x00\x30\x01\x12O\n\x16\x43reateHistoricalStream\x12\x17.HistoricalTradeRequest\x1a\x18.HistoricalTradeResponse\"\x00\x30\x01\x62\x06proto3'
)




_TRADEDATA = _descriptor.Descriptor(
  name='TradeData',
  full_name='TradeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='TradeData.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='security_id', full_name='TradeData.security_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='side', full_name='TradeData.side', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='TradeData.price', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='TradeData.quantity', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=119,
)


_TRADEARBITRAGEREQUEST = _descriptor.Descriptor(
  name='TradeArbitrageRequest',
  full_name='TradeArbitrageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trade', full_name='TradeArbitrageRequest.trade', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_simulations', full_name='TradeArbitrageRequest.num_simulations', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_arbitrages', full_name='TradeArbitrageRequest.id_arbitrages', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_dummy', full_name='TradeArbitrageRequest.num_dummy', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=238,
)


_TRADEARBITRARYREQUEST = _descriptor.Descriptor(
  name='TradeArbitraryRequest',
  full_name='TradeArbitraryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trade', full_name='TradeArbitraryRequest.trade', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_simulations', full_name='TradeArbitraryRequest.num_simulations', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_securities', full_name='TradeArbitraryRequest.num_securities', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=339,
)


_HISTORICALTRADEREQUEST = _descriptor.Descriptor(
  name='HistoricalTradeRequest',
  full_name='HistoricalTradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='security_id', full_name='HistoricalTradeRequest.security_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=386,
)


_HISTORICALTRADERESPONSE = _descriptor.Descriptor(
  name='HistoricalTradeResponse',
  full_name='HistoricalTradeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='history_found', full_name='HistoricalTradeResponse.history_found', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trade', full_name='HistoricalTradeResponse.trade', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=463,
)

_TRADEARBITRAGEREQUEST.fields_by_name['trade'].message_type = _TRADEDATA
_TRADEARBITRARYREQUEST.fields_by_name['trade'].message_type = _TRADEDATA
_HISTORICALTRADERESPONSE.fields_by_name['trade'].message_type = _TRADEDATA
DESCRIPTOR.message_types_by_name['TradeData'] = _TRADEDATA
DESCRIPTOR.message_types_by_name['TradeArbitrageRequest'] = _TRADEARBITRAGEREQUEST
DESCRIPTOR.message_types_by_name['TradeArbitraryRequest'] = _TRADEARBITRARYREQUEST
DESCRIPTOR.message_types_by_name['HistoricalTradeRequest'] = _HISTORICALTRADEREQUEST
DESCRIPTOR.message_types_by_name['HistoricalTradeResponse'] = _HISTORICALTRADERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeData = _reflection.GeneratedProtocolMessageType('TradeData', (_message.Message,), {
  'DESCRIPTOR' : _TRADEDATA,
  '__module__' : 'trade_simulation_pb2'
  # @@protoc_insertion_point(class_scope:TradeData)
  })
_sym_db.RegisterMessage(TradeData)

TradeArbitrageRequest = _reflection.GeneratedProtocolMessageType('TradeArbitrageRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADEARBITRAGEREQUEST,
  '__module__' : 'trade_simulation_pb2'
  # @@protoc_insertion_point(class_scope:TradeArbitrageRequest)
  })
_sym_db.RegisterMessage(TradeArbitrageRequest)

TradeArbitraryRequest = _reflection.GeneratedProtocolMessageType('TradeArbitraryRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADEARBITRARYREQUEST,
  '__module__' : 'trade_simulation_pb2'
  # @@protoc_insertion_point(class_scope:TradeArbitraryRequest)
  })
_sym_db.RegisterMessage(TradeArbitraryRequest)

HistoricalTradeRequest = _reflection.GeneratedProtocolMessageType('HistoricalTradeRequest', (_message.Message,), {
  'DESCRIPTOR' : _HISTORICALTRADEREQUEST,
  '__module__' : 'trade_simulation_pb2'
  # @@protoc_insertion_point(class_scope:HistoricalTradeRequest)
  })
_sym_db.RegisterMessage(HistoricalTradeRequest)

HistoricalTradeResponse = _reflection.GeneratedProtocolMessageType('HistoricalTradeResponse', (_message.Message,), {
  'DESCRIPTOR' : _HISTORICALTRADERESPONSE,
  '__module__' : 'trade_simulation_pb2'
  # @@protoc_insertion_point(class_scope:HistoricalTradeResponse)
  })
_sym_db.RegisterMessage(HistoricalTradeResponse)



_TRADESIMULATION = _descriptor.ServiceDescriptor(
  name='TradeSimulation',
  full_name='TradeSimulation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=466,
  serialized_end=694,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateArbitrageStream',
    full_name='TradeSimulation.CreateArbitrageStream',
    index=0,
    containing_service=None,
    input_type=_TRADEARBITRAGEREQUEST,
    output_type=_TRADEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateArbitraryStream',
    full_name='TradeSimulation.CreateArbitraryStream',
    index=1,
    containing_service=None,
    input_type=_TRADEARBITRARYREQUEST,
    output_type=_TRADEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateHistoricalStream',
    full_name='TradeSimulation.CreateHistoricalStream',
    index=2,
    containing_service=None,
    input_type=_HISTORICALTRADEREQUEST,
    output_type=_HISTORICALTRADERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADESIMULATION)

DESCRIPTOR.services_by_name['TradeSimulation'] = _TRADESIMULATION

# @@protoc_insertion_point(module_scope)
